### ISSUE TITLE
Download to share-online.biz

### ISSUE THREAD

**Issue by beacherpille88** [mcrapet/plowshare#100]
Hello,

I believe the download via share-online premium account doesnt work anymore.

Im not sure, whats going wrong. I download the link an login with "-a username:password". I dont get any captchas, but the download only uses 300kB/s.

I already made a support request with share-online and they said, my account wasnt used since lots of days. (two days ago I was using it)

Can anyone confirm?

**Comment by mcrapet** [comment]
Hi,
Please submit this issue in [plowshare-modules-legacy repository](https://github.com/mcrapet/plowshare-modules-legacy/issues/).
This is the core repository, and the issue is related to a module.
