### ISSUE TITLE
oboom download does not work

### ISSUE THREAD

**Issue by sshtmc** [mcrapet/plowshare#101]
Hi,

I just tried downloading a file from oboom.com and got the following failure:

```
⟫ plowdown https://www.oboom.com/XXXXXX/
Starting download (oboom): https://www.oboom.com/XXXXXX/
Local image: /tmp/plowdown.24434.23215.recaptcha.jpg
Using DeathByCaptcha service (XXXXXXXXX)
Waiting 4 seconds... done        
Download auth failed. Remote error (500): 'Update needed'.
parse failed (sed): "/./ s/^\[200,"\([^"]\+\).*$/\1/p" (skip 0)
Failed inside oboom_download(), line 559, oboom.sh
Failed inside oboom_download() [1]
```

I'm using the latest plowdown release from this repo: v2.1.7

What might give you an insight is the page that is returned by oboom.com:\

```
[500,"Update needed","Only coin-hive.com captcha is allowed currently. Use public key MaFDtZCyUne9nXFVkmbdYC96jNEuQmst and 1024 hashes"]
```

Any hints or suggestions?
Thanks for this cool tool!

**Comment by mcrapet** [comment]
Hi,
Please submit this issue in [plowshare-modules-legacy repository](https://github.com/mcrapet/plowshare-modules-legacy/issues/).
This is the core repository, and the issue is related to a module.
