### ISSUE TITLE
Filename has no length

### ISSUE THREAD

**Issue by juanlucky** [mcrapet/plowshare#103]
Hi,
I encounter a problem downloading files from uptobox on geexbox(cubox-i) OS. I tried several files and I always have this error "remote filename has no length". I tried the same files with the same plowdown script files on Ubuntu and the download is ok.
I don't know if the missing recode command could be the pb (optional in the documentation).
This command is not available on geexbox.
I have enough space on the disk to download the files.

Here is a trace :
root@geexbox:~# plowdown -ajuxxx:xxxx http://uptobox.com/yaz5oxu8ylfx
Starting download (uptobox): http://uptobox.com/yaz5oxu8ylfx
Starting login process: juxxx/****************
recode: command not found
called with arguments: html..utf8
File URL: http://www4.uptobox.com/d/uuy6t2tehoj4mwcqpv6pg3tcmgul67f6wz7vtbovlwwuerpugontqunf6ztwmhhzxd4v3j6zshludga/Marie.Francine.2017.FRENCH.BDRip.XviD.avi
Filename: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Remote filename has no length!
  0  695M    0  1161    0     0   2887      0 70:08:22 --:--:-- 70:08:22  3172
curl: (23) Failed writing body (0 != 1161)
curl: write failed, disk full?

**Comment by juanlucky** [comment]
with the -v4 log

`rep: === SYSTEM INFO BEGIN ===
rep: [mach] geexbox armv7 linux-gnueabihf armv7-openbricks-linux-gnueabihf
rep: [bash] 4.3.30(1)-release
rep: [curl] curl 7.53.1 (armv7-openbricks-linux-gnueabihf) libcurl/7.53.1 OpenSSL/1.0.2l zlib/1.2.8
rep: [sed ] This is not GNU sed version 4.0
rep: [lib ] '/root/plowshare'
rep: === SYSTEM INFO END ===
rep: plowdown version GIT-snapshot
[0;33mStarting download (uptobox): http://uptobox.com/yaz5oxu8ylfx[0m
[0;33mStarting login process: juxxx/****************[0m
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent --cookie-jar /tmp/plowdown.10647.9710 --data op=login&redirect=&login=juxxx&password=xxx https://login.uptobox.com/logarithme
rep: Received 44 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:{"success" : "OK", "msg" : "Please wait..."}
rep: === CURL END ===
rep: === COOKIE BEGIN ===
rep:# Netscape HTTP Cookie File
rep:# https://curl.haxx.se/docs/http-cookies.html
rep:# This file was generated by libcurl! Edit at your own risk.
rep:
rep:#HttpOnly_.uptobox.com	TRUE	/	FALSE	1539031928	__cfduid	d96829cb7a1aa888a1fd4abe2dd2a56051507495928
rep:.uptobox.com	TRUE	/	FALSE	1510087928	xfss	zip8thzgfxfaiq1g
rep: === COOKIE END ===
dbg: Successfully logged in
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent -b /tmp/plowdown.10647.9710 http://uptobox.com/?op=my_account
rep: Received 14411 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:<!DOCTYPE html>
rep:<html>
rep:<head>
rep:<title>Uptobox - Easy way to share your files</title>
rep:<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
rep:<link rel="stylesheet" href="//static.uptobox.com/css/jquery.fileupload.css">
rep:<link rel="stylesheet" href="//static.uptobox.com/css/jquery.fileupload-ui.css">
rep:<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css">
rep:<link rel="stylesheet" type="text/css" href="//static.uptobox.com/main.css" />
rep:<meta http-equiv="Content-Type" content="text/html; charset=utf-8" xml:lang="fr" lang="fr" />
rep:<meta name="description" content="Uptobox - Hébergeur de fichiers en ligne simple et rapide, téléchargement sans limite de vitesse.">
rep:<meta name="keywords" content="hébergeur, stockage, upload, fichiers, 50go, partage de fichiers, hébergeur de fichiers">
rep:
rep:<script type="text/javascript">
rep:_atrk_opts = { atrk_acct:"iBExe1a8DT002D", domain:"uptobox.com",dynamic: true};
rep:(function() { var as = document.createElement('script'); as.type = 'text/javascript'; as.async = true; as.src = "https://d31qbv1cthcecs.cloudfront.net/atrk.js"; var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(as, s); })();
rep:</script>
rep:<noscript><img src="https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=iBExe1a8DT002D" style="display:none" height="1" width="1" alt="" /></noscript>
rep:
rep:
rep:<script src="//static.uptobox.com/jquery-1.8.3.min.js"></script>
rep:<script language="JavaScript" type="text/javascript" CHARSET="UTF-8" src="//static.uptobox.com/jquery.uniform.min.js"></script>
rep:<script language="JavaScript" type="text/javascript" CHARSET="UTF-8" src="//static.uptobox.com/jquery.tipsy.js"></script>
rep:<script src="//static.uptobox.com/bootstrap.min.js"></script>
rep:<script src="//static.uptobox.com/main.js"></script>
rep:<script type="text/javascript">!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
rep:<script type="text/javascript" src="//static.uptobox.com/js/c.ad6media.fr_l.js"></script>
rep:<script type="text/javascript">
rep:	  window.___gcfg = {lang: 'fr'};
rep:	  (function() {
rep:	    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
rep:	    po.src = 'https://apis.google.com/js/plusone.js';
rep:	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
rep:	  })();
rep:	</script>
rep:<script language="JavaScript" type="text/javascript" CHARSET="UTF-8" src="//static.uptobox.com/xupload.js"></script>
rep:<script>
rep:  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
rep:  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
rep:  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
rep:  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
rep:
rep:  ga('create', 'UA-21628240-1', 'uptobox.com');
rep:  ga('send', 'pageview');
rep:
rep:</script>
rep:<script type='text/javascript'></script><noscript><a href='http://ads2.uptobox.com/www/delivery/ck.php?n=a90c64cc&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://ads2.uptobox.com/www/delivery/avw.php?zoneid=125&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a90c64cc' border='0' alt='' /></a></noscript>
rep:
rep:<script>
rep:$(document).ready(function () {
rep:    updateContainer();
rep:    $(window).resize(function() {
rep:        updateContainer();
rep:    });
rep:});
rep:function updateContainer() {
rep:    var $containerWidth = $(window).width();
rep:    // si la largeur est inferieur à 900px
rep:    if ($containerWidth <= 900) {
rep:    	// on cache les elements useless du menu
rep:        $('#accueil').css({
rep:            display: 'none',
rep:        });
rep:        $('#support').css({
rep:            display: 'none',
rep:        });
rep:        $('#inscription').css({
rep:            'border-right': '1.5px solid #000000',
rep:        });
rep:        // si taille vraiment mini on cache le menu 
rep:        if ($containerWidth <= 700) {
rep:	        $('.menu').css({
rep:	            display: 'none',
rep:	        });
rep:	    }
rep:	    else {
rep:	    	$('.menu').css({
rep:	            display: 'inline-block',
rep:	        });
rep:	    }
rep:    }
rep:    // si la largeur est superieur à 900px
rep:    if ($containerWidth > 900) {
rep:        $('#accueil').css({
rep:            display: 'inline-block',
rep:        });
rep:        $('#support').css({
rep:            display: 'inline-block',
rep:        });
rep:    }
rep:}
rep:</script>
rep:
rep:</head>
rep:<body>
rep:<div id="container">
rep:
rep:<div id="header">
rep:<a href="http://uptobox.com"><img class="logo_header" src="//static.uptobox.com/images/logo.png" width="163" height="29" alt="UptoBox"></a>
rep:
rep:<ul class="menu">
rep:<li id="accueil">
rep:<a class="nav_link" href="http://uptobox.com">Home</a>
rep:</li><li>
rep:<a class="nav_link" href="http://uptobox.com/?op=payments">
rep:Renew Premium
rep:<div class="premium_time"><strong>Premium-Account expire: 22 September 2018 22:55</strong></div>
rep:</a>
rep:</li><li>
rep:<a class="nav_link" href="http://uptobox.com/?op=my_account">My account</a>
rep:</li><li>
rep:<a class="nav_link" href="http://uptobox.com/?op=my_files">My files</a>
rep:</li><li id="support">
rep:<a class="nav_link" href="http://support.uptobox.com">Support</a>
rep:</li><li style="border-right: 1.5px solid #000000;">
rep:<a class="nav_link" href="http://uptobox.com/?op=logout">Logout</a>
rep:</li>
rep:</ul>
rep:
rep:<ul class="country_block">
rep:<li class="default_country">
rep:english
rep:</li>
rep:<ul class="switch_lang">
rep:<li><a class="nav_link" href="http://uptobox.com/?op=change_lang&amp;lang=english"><img style="margin-right:5px;" src="//static.uptobox.com/images/flag_uk.png" width="16" height="11" alt="English" />English</a></li>
rep:<li><a class="nav_link" href="http://uptobox.com/?op=change_lang&amp;lang=french"><img style="margin-right:5px;" src="//static.uptobox.com/images/flag_fr.png" width="16" height="11" alt="Français" />Français</a></li>
rep:<li><a class="nav_link" href="http://uptobox.com/?op=change_lang&amp;lang=indonesia"><img style="margin-right:5px;" src="//static.uptobox.com/images/flag_id.png" width="16" height="11" alt="Indonesian" />Bahasa Indonesia</a></li>
rep:<li><a class="nav_link" href="http://uptobox.com/?op=change_lang&amp;lang=arabic"><img style="margin-right:5px;" src="//static.uptobox.com/images/flag_al.png" width="18" height="13" alt="Arabic" />العربية</a></li>
rep:</ul>
rep:</ul>
rep:
rep:
rep:<div style="height: 50px; background-color: #FFF"><font color="red" size="3" style=""><b>Ne laissez personne intercepter vos informations de navigation, cryptez et protégez-vous avec notre partenaire en <a target="_blank" href="https://partner.zenmate.com/go.cgi?pid=1127&wmid=cc&cpid=1&target=http://pages.zenmate.com/hidemyip/?zm_spc_promo_code=PACKYOURZENMATE&utm_source=1127&utm_medium=affiliate&utm_content=deeplink">cliquant ici</a>.
rep:<br />Never let anyone intercept your browsing informations, encrypt and protect yourself with our partner by <a target="_blank" href="https://partner.zenmate.com/go.cgi?pid=1127&wmid=cc&cpid=1&target=http://pages.zenmate.com/hidemyip/?zm_spc_promo_code=PACKYOURZENMATE&utm_source=1127&utm_medium=affiliate&utm_content=deeplink">clicking here</a>.</b></font></div>
rep:</div>
rep:
rep:<div id="container_page">
rep:<div class="bg_page">
rep:<script>
rep:$('#container_page').css("background", "url(./images/background_alternate.png ) no-repeat 50% 50px");
rep:</script>
rep:
rep:<div style="margin-top: 0px; margin-left: auto; margin-right: auto; width: 1000px;">
rep:<div class="para_title">My account</div>
rep:<div class="tabberlive" style="text-align: left;">
rep:
rep:<form method="POST" onSubmit="if(this.password_new.value!=this.password_new2.value){alert('Passwords do not match');return false;}return true;">
rep:<input type="hidden" name="op" value="my_account">
rep:<input type="hidden" name="token" value="43efa63e29dda8024690093ffcdd9806">
rep:<table class="files">
rep:<thead>
rep:<tr>
rep:<td class="thead_green" style="padding-left: 30px; border-radius:10px 10px 0px 0px;">
rep:Premium member
rep:</td>
rep:</tr>
rep:</thead>
rep:<tbody>
rep:<tr><td class="green_tab_cell"><strong>Hello <strong>juanlucky</strong></tr>
rep:<tr><td class="green_tab_cell"><strong>Premium-Account expire: </strong><span style="font-weight:bold; color:#E10000;">22 September 2018 22:55</span> <a href="http://uptobox.com/?op=payments" class="green_link" style="float:right;">Renew premium</a></tr>
rep:<tr><td class="green_tab_cell"><strong>Number of points UTB :</strong> <span style="font-weight:bold; color:#E10000;">0</span> <span style="font-size:10px; margin-left:20px;">*1 Uptobox point = 1000 downloads on Uptobox or 1000 views on Uptostream.</span> <a href="./?op=request_premium" class="green_link" style="float:right;">Convert my points</a></tr>
rep:<tr><td class="green_tab_cell"><strong>Add a premium key:</strong><br /><input id="appendedInputButton" type="text" name="premium_key" value="" size=24 class="span2" style="margin-right:15px;"><button type="submit" name="premium_key_apply" value="" class="btn">Apply</button><br /><br /><a href="http://uptobox.com/?op=resellers_list">Buy a premium key</a></tr>
rep:<tr><td class="green_tab_cell">My affiliate link : <a href="http://uptobox.com/affiliate/342320" class="green_link">http://uptobox.com/affiliate/342320</a></tr>
rep:<tr><td class="green_tab_cell">My referrals : <a href="?op=my_referrals" class="green_link">0</a></tr>
rep:</tbody>
rep:</table>
rep:
rep:<table class="files">
rep:<thead>
rep:<tr>
rep:<td class="thead_green" style="padding-left: 30px; border-radius:10px 10px 0px 0px;">
rep:Configuration
rep:</td>
rep:</tr>
rep:</thead>
rep:<tbody>
rep:<tr><td class="green_tab_cell"><div class="text_input" style="margin-top:0;">E-mail</div><input type="text" name="usr_email" value="kishibasensei-info@yahoo.fr" placeholder=""></tr>
rep:<tr><td class="green_tab_cell"><div class="text_input" style="margin-top:0;">New password</div><input type="password" name="password_new" placeholder=""></tr>
rep:<tr><td class="green_tab_cell"><div class="text_input" style="margin-top:0;">Confirm your new password</div><input type="password" name="password_new2" placeholder=""></tr>
rep:<tr><td class="green_tab_cell"><input type="checkbox" name="usr_direct_downloads" id="cdl" value="1" checked> <label for="cdl">Direct-downloads</b></label> <small>(Premium only)</small></tr>
rep:<tr><td class="green_tab_cell"><input type="checkbox" name="usr_ssl_downloads" id="cd2" value="1"> <label for="cd2">Secure download (SSL) </b></label> <small>(Premium only)</small></tr>
rep:<tr><td class="green_tab_cell"><a href="http://www.nas-forum.com/forum/topic/44084-module-download-station-uptobox-host-file-uptobox/">Direct download on your NAS (Download Station)</a></tr>
rep:<tr><td class="green_tab_cell"><b>Security lock</b>
rep:<span style="font-weight:bold; color:#E10000;">OFF</span> <a href="?op=my_account&enable_lock=1">Enable</a>
rep:</tr>
rep:</tbody>
rep:</table>
rep:<div class="function_block">
rep:<input class="button_upload green" type="submit" name="settings_save" value="Save Settings">
rep:</div>
rep:</form><br>
rep:</div>
rep:</div>
rep:</div>
rep:</div>
rep:</div>
rep:
rep:<div id="footer">
rep:<div class="footer_content">
rep:<div class="footer_leftcol">
rep:
rep:
rep:
rep:
rep:
rep:<ul class="footer_menu">
rep:<li><a class="nav_link_footer" href="http://uptobox.com">Home</a></li>
rep:<li><a class="nav_link_footer" href="faq.html">Q&A</a></li>
rep:
rep:<li><a class="nav_link_footer" href="tos.html">ToS</a></li>
rep:<li><a class="nav_link_footer" href="http://uptobox.com/?op=advertising">Advertisers</a></li>
rep:<li><a class="nav_link_footer" href="http://uptobox.com/?op=reseller_program">Resellers</a></li>
rep:<li><a class="nav_link_footer" href="mailto:uptobox.abuse@gmail.com">Abuse</a></li>
rep:<li><a class="nav_link_footer" href="http://support.uptobox.com">Support</a></li>
rep:<li><a class="nav_link_footer" href="http://uptobox.com/pages/about_us.html">About us</a></li>
rep:</ul>
rep:</div>
rep:<div class="footer_rightcol">
rep:
rep:<a href="https://www.facebook.com/Uptobox" rel="nofollow" target="_blank">
rep:<img src="//static.uptobox.com/images/facebook_icon.png" width="121px" height="25px" alt="Facebook" />
rep:</a>
rep:<a href="https://twitter.com/Uptobox_com" rel="nofollow" target="_blank">
rep:<img src="//static.uptobox.com/images/twitter_icon.png" width="45px" height="25px" alt="Twitter" />
rep:</a>
rep:</div>
rep:</div>
rep:</div>
rep:<div id="copyright">
rep:<div class="copyright_content">
rep:<div class="copyright_text" style="font-size:12px;">© 2011 - 2017 <a href="#" class="blue_link">Uptobox.com</a> - All rights reserved</div>
rep:<div class="socials">
rep:<iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2FUptobox&amp;send=false&amp;layout=button_count&amp;width=0&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=tahoma&amp;height=21&amp;appId=94277056922" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:117px; height:21px;" allowTransparency="true"></iframe>
rep:</div>
rep:<div class="copyright_text" style="font-size:11px; margin-top:2px; float:right;"></div>
rep:</div>
rep:</div>
rep:<div id='biscuitNomNomNom'>
rep:</div>
rep:<div id='biscuitMiamMiamMiam'>
rep:</div>
rep:<script>
rep:	function getCookie(name) {
rep:		var re = new RegExp(name + "=([^;]+)");
rep:	    var value = re.exec(document.cookie);
rep:	    return (value != null) ? unescape(value[1]) : null;
rep:	 }
rep:
rep:	var cookie = getCookie("xfss");
rep:	var lang = getCookie("lang");
rep:
rep:   if (cookie != null) {
rep:   	$('#biscuitNomNomNom').html('<iframe width="0" height="0" src="https://uptostream.com/biscuit.html?xfss=' + cookie + '&lang=' + lang + '" frameborder="0" ></iframe>');
rep:   }
rep:</script>
rep:
rep:
rep:<script type="text/javascript">
rep:  window._taboola = window._taboola || [];
rep:  _taboola.push({flush: true});
rep:</script>
rep:</body>
rep:</html>
rep: === CURL END ===
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent -I -b /tmp/plowdown.10647.9710 http://uptobox.com/yaz5oxu8ylfx
rep: Received 389 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:HTTP/1.1 302 Found
rep:Date: Sun, 08 Oct 2017 20:52:09 GMT
rep:Content-Type: text/plain; charset=utf-8
rep:Connection: keep-alive
rep:Cf-Railgun: 9c0db72caf stream 0.000000 0200 e6be
rep:Location: http://www4.uptobox.com/d/uuy6t2tehoj4mwcqpv6pg3tcmgul67f6wz7vtbovlwwuerpugontrmfp6ztwmhhzxd4v3j6zshlucwq/Marie.Francine.2017.FRENCH.BDRip.XviD.avi
rep:Server: cloudflare-nginx
rep:CF-RAY: 3aabfb78b24c08ea-CDG
rep:
rep: === CURL END ===
rep: html_to_utf8: use recode
recode: command not found
called with arguments: html..utf8
[0;33mFile URL: http://www4.uptobox.com/d/uuy6t2tehoj4mwcqpv6pg3tcmgul67f6wz7vtbovlwwuerpugontrmfp6ztwmhhzxd4v3j6zshlucwq/Marie.Francine.2017.FRENCH.BDRip.XviD.avi[0m
[0;33mFilename: [0m
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --fail --globoff -w %{http_code}\t%{size_download} -o  http://www4.uptobox.com/d/uuy6t2tehoj4mwcqpv6pg3tcmgul67f6wz7vtbovlwwuerpugontrmfp6ztwmhhzxd4v3j6zshlucwq/Marie.Francine.2017.FRENCH.BDRip.XviD.avi
rep: Received 51 bytes. DRETVAL=23
rep: === CURL BEGIN ===
rep:curl: (23) Failed writing body (0 != 1161)
rep:200	1161
rep: === CURL END ===
[0;31mcurl: write failed, disk full?[0m
/bin/plowdown: line 581: read: curl: (23) Failed writing body (0 != 1161): syntax error in expression (error token is ": (23) Failed writing body (0 != 1161)")
[0;33m[0m`

**Comment by mcrapet** [comment]
Not the proper repository, see plowshare-modules-legacy.
