### ISSUE TITLE
Plowshare doesn't work

### ISSUE THREAD

**Issue by Fu2chN** [mcrapet/plowshare#107]
Hi
I can not use plowshare I fall on:

plowdown -a 'USER:PASSW' LINKSUPTOBOX
```
grep_form_by_name failed (sed): "name=F1"
Failed inside uptobox_download() [1]
```

plowup uptobox -a 'USER:PASSW' FILES
```
grep_form_by_id failed (sed): "id=fileupload"
Failed inside uptobox_upload() [1]
```
What is my mistake?

I install them like this:
apt-get install git curl -y
cd /tmp
git clone https://github.com/mcrapet/plowshare.git
cd plowshare
make install
cd ..
rm -rf plowshare

I'm on Debian 9

Thank for help.

**Comment by mcrapet** [comment]
Hi,

`uptobox` module is probably broken.
This is the core repository, for modules issues see here: [plowshare-modules-legacy repository](https://github.com/mcrapet/plowshare-modules-legacy/issues/).

**Comment by Fu2chN** [comment]
Ok.
