### ISSUE TITLE
1fichier and password

### ISSUE THREAD

**Issue by Nico83500** [mcrapet/plowshare#108]
Hi,
I would like to donwload a file from 1fichier but I get this message : 
> login@SERVER:~$ plowdown -a USER:PASSWORD -p PASS https://1fichier.com/?xxxxxxxxxx
> Starting download (1fichier): https://1fichier.com/?xxxxxxxxx
> Starting login process: USER/********
> This must be a direct download link with password, filename will be wrong!
> You must provide a valid password

If I do it manually, it works but not with plowdown. Is it a known issue ?
Thank you !

**Comment by mcrapet** [comment]
Hi,

This is the core of Plowshare here.
For modules issues, please create an issue here:
https://github.com/mcrapet/plowshare-modules-legacy/issues

Note: Modules are not maintened anymore.
