### ISSUE TITLE
Multiple connections ?

### ISSUE THREAD

**Issue by TEALC82** [mcrapet/plowshare#109]
Hello, I would like to know if it is possible to use several connections on the same file to accelerate the upload or download on a premium account?

$ plowdown -a user:pass -maxco 5 https://url_file

Thank you in advance.

PS: sorry for me english

**Comment by mcrapet** [comment]
Hi,
You can do it indirectly using `aria2c`.
I provided an example in the main markdown doc, search:
*Example 3: Use multiple connections for final download (usually only for premium account users)*

Notice that you probably need a premium account. Hosters doesn't allow multiple connections with anonymous/free accounts.
