### ISSUE TITLE
MultiUp

### ISSUE THREAD

**Issue by ghost** [mcrapet/plowshare#111]
Hi,

Can you check/update multiup.org ?
It can handle 100gb now

Regards

**Comment by hemiad** [comment]
+1 there a error parse_json failed (json): "hosts" ...

**Comment by mcrapet** [comment]
Hi,

This is the core of Plowshare here.
For modules issues, please create an issue here:
https://github.com/mcrapet/plowshare-modules-legacy/issues

Note: Modules are not maintened anymore.
