### ISSUE TITLE
zippyshare failed to download

### ISSUE THREAD

**Issue by pplexr** [mcrapet/plowshare#117]
giving error:

/tmp/plowdown.11894.11919.js:18: TypeError: document.getElementById("omg").getAttribute is not a function

**Comment by Henrymccormack** [comment]
I get the exact same error:
```
Starting download (zippyshare): http://www44.zippyshare.com/v/xxxxxxxxxx/file.html
/var/folders/wy/x5vh2c3s55lg7j1xt0g6nqbw0000gn/T//plowdown.39230.25625.js:18: TypeError: document.getElementById("omg").getAttribute is not a function
Output URL is not valid: http://www44.zippyshare.com
```

**Comment by skw4y** [comment]
The command was working fine yesterday but now I've got the same error: 

```
Starting download (zippyshare): https://www101.zippyshare.com/v/XXX/file.html
/tmp/plowdown.24834.23526.js:18:0 TypeError: document.getElementById(...).getAttribute is not a function
Output URL is not valid: https://www101.zippyshare.com
```

**Comment by thornick** [comment]
had the same error - and see no fix published yet. In the meantime you can manipulate the DOM by - 'awk' the getattribute line and replace it by `var d = 2; `then it runs as usual.
Must admit I do not know yet why it breaks here.
Very nice code anyway ...

**Comment by rossington** [comment]
Thanks for the hint, @QUEHLE.

To fix this, make the following changes to zippyshare.sh (check in /usr/share/plowshare/modules/zippyshare.sh or ~/.config/plowshare/modules.d/legacy.git/zippyshare.sh)

```diff
@@ -145,6 +145,9 @@
           /^<script type="text\/javascript">/,/^<\/script>/{/^[[:space:]]*</!p}
           }' <<< "$PAGE")
 
+	VARD_REP_SUBSTR="document.getElementById('omg').getAttribute('class')"
+	JS="${JS/$VARD_REP_SUBSTR/2}"
+
     PART_URL=$(echo "var elts = new Array();
         var document = {
           getElementById: function(id) {
```

**Comment by mcrapet** [comment]
Hi,

This is the core of Plowshare here.
For modules issues, please create an issue here:
https://github.com/mcrapet/plowshare-modules-legacy/issues

Note: Modules are not maintened anymore.
