### ISSUE TITLE
Making things clearer for people who is looking for Plowshare

### ISSUE THREAD

**Issue by Ganton** [mcrapet/plowshare#12]
Hi!

People look for Plowshare and they find:
- https://github.com/plowshare    (and inside it, https://github.com/plowshare/plowshare)
- https://github.com/mcrapet/plowshare

To people, the first place looks like a more "official" place to people, due to its address, but the second place has a newer version of the software. In Github people see the description of both projects (brought from the "README.md" file) and it's the same, so they think "it's the same project", but it's not the same software.

To avoid confusions to people, and to inform them, could e.g. the "README.md" file show why this repository is different?

Thank you for Plowshare!

**Comment by mcrapet** [comment]
Hi,
You are at the right place.
I asked the owner of https://github.com/plowshare to delete this _plowshare_ organization.

Regards,
Matthieu

**Comment by Ganton** [comment]
In https://code.launchpad.net/plowshare, https://www.archlinux.org/packages/community/any/plowshare/, https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/net-misc/plowshare/metadata.xml?view=markup and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780311 the upstream url is https://github.com/mcrapet/plowshare. 

Even in the other repository, in https://github.com/plowshare/plowshare/blob/master/INSTALL, it's written "[...] https://github.com/mcrapet/plowshare-modules-legacy [...]", not "https://github.com/plowshare/[...]".

**Comment by Ganton** [comment]
FWIW: The trademark "Plowshare" for this kind of software... has to have an owner. Anyone can fork free/libre software, but using the same name is not allowed (in order to avoid confusions, etc.). I am not a lawyer, by the way :-)

**Comment by mcrapet** [comment]
https://github.com/mcrapet/plowshare is the official place.

https://github.com/plowshare/ has **not** been created by me. I sent a message to the owner, but he didn't response yet. The better would be to delete https://github.com/plowshare/ to not confuse people.

**Comment by Ganton** [comment]
Yes.

Although it would be really good to inquire who owns the trademark "Plowshare" and to manage that, to avoid that impostors frame people telling them that they are downloading "Plowshare", and, still worse, that they register the trademark of the software "Plowshare", "Plowdown", and so... the true Plowshare developers have to change the word "Plowshare", "Plowdown" in all their software, links, repository names, etc., etc. :-(

**Comment by msdos** [comment]
I think it's hard to ask to delete the plowshare organization if you don't own the trademark. Maybe you should contact github staff to check what you can do? (Specially because you came from Google Code from a _long time_ with this username)

Well, at least https://github.com/plowshare/plowshare was deleted. So it's up to you if you think this issue can be closed.

**Comment by zodman** [comment]
confirmed!
