### ISSUE TITLE
download uploaded.net recaptcha error

### ISSUE THREAD

**Issue by ghost** [mcrapet/plowshare#120]
I have this message when i try to download a file on uploaded.net :

"Enter captcha response (drop punctuation marks, case insensitive): display: Not a JPEG file: starts with 0x3c 0x48 `/tmp/plowdown.16743.31273.recaptcha.jpg' @ error/jpeg.c/JPEGErrorHandler/340.
display: no decode delegate for this image format `' @ error/constitute.c/ReadImage/556."

Is it possible to solve this ?

**Comment by mcrapet** [comment]
Hi,

This is the core of Plowshare here.
For modules issues, please create an issue here:
https://github.com/mcrapet/plowshare-modules-legacy/issues

Note: Modules are not maintened anymore.
