### ISSUE TITLE
Turbobit not working

### ISSUE THREAD

**Issue by Gercekefsane** [mcrapet/plowshare#122]
Starting download (turbobit): http://turbobit.net/rsfohw45uk32.html
parse failed (sed): "/<title>/ s/^[[:blank:]]*Download \(.\+\). Free.*$/\1/p" (skip 1)
Failed inside turbobit_download(), line 169, turbobit.sh
Failed inside turbobit_download() [1]

**Comment by mcrapet** [comment]
Hi,

This is the core of Plowshare here.
For modules issues, please create an issue here:
https://github.com/mcrapet/plowshare-modules-legacy/issues

Note: Modules are not maintened anymore.
