### ISSUE TITLE
plowup multiup_org : parse_json failed (json): "error"

### ISSUE THREAD

**Issue by maruashok** [mcrapet/plowshare#124]
Input : plowup -a 'myuser:mypass' multiup_org Test.txt
Output :
parse_json failed (json): "error"
Failed inside multiup_org_upload(), line 76, multiup_org.sh
Remote error: 
Failed inside multiup_org_upload() [1]

**Comment by mcrapet** [comment]
Hi,

This is the core of Plowshare here.
For modules issues, please create an issue here:
https://github.com/mcrapet/plowshare-modules-legacy/issues

Note: Modules are not maintened anymore.
