### ISSUE TITLE
Can't Download from Uploaded.net after a certain amount of downloaded GB

### ISSUE THREAD

**Issue by Hamm3rhart** [mcrapet/plowshare#125]
Hello,

my problem is that, when i start plowdown with this command 
`plowdown -a 'username:password' -m /path/to/my/Links.txt
`
it get this error after a certain amount of time

> Starting download (uploaded_net): http://uploaded.net/file/LINK
Starting login process: username/************************
parse_attr failed (sed): "/stor[[:digit:]]\+\./ action="
Failed inside uploaded_net_download(), line 319, uploaded_net.sh
Failed inside uploaded_net_download() [1]
Starting download (uploaded_net): http://uploaded.net/file/LINK2
parse_attr failed (sed): "/stor[[:digit:]]\+\./ action="
Failed inside uploaded_net_download(), line 319, uploaded_net.sh
Failed inside uploaded_net_download() `[1]`

First i could download round about 16GB and than the problem from above started. I don't know why this happens.

System: Ubuntu 18.04.2 LTS
Version of plowshare: Latest (Reinstalled it severaltimes through apt-get install plowshare)

Could someone please help me?
Thanks

**Comment by mcrapet** [comment]
Hi,

This is the core of Plowshare here.
For modules issues, please create an issue here:
https://github.com/mcrapet/plowshare-modules-legacy/issues

Note: Modules are not maintened anymore.
