### ISSUE TITLE
Retrying doesnt work

### ISSUE THREAD

**Issue by docgonzo2015** [mcrapet/plowshare#126]
The Option -r doesnt work well at the module rapidgator.

Starting upload (rapidgator): file.rar
Destination file: file.rar
Starting login process: mail/************
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1001M    0   109  100 1001M      7  65.5M  0:00:15  0:00:15 --:--:--     0
Waiting 5 seconds... done
**There was an error uploading the file.
Output URL expected**

I use plowup -**-max-retries=2** --cache=shared

**Comment by mcrapet** [comment]
Not the proper repository, see plowshare-modules-legacy.
