### ISSUE TITLE
Zippyshare Size Increase

### ISSUE THREAD

**Issue by PuffinAround** [mcrapet/plowshare#129]
Can you please increase the upload size of the Zippyshare host to 500 MB?

**Comment by mason1171** [comment]
By default the limit is 200MB. Follow these steps to fix the problem:
1. cd to the modules location
2. use 'nano' to open up zippyshare file: 'sudo nano zippyshare.sh'
3. Use CTRL+W to search for 'filesize' and edit the max file size from 200MB to 500MB (or any other size you prefer).
4. Save and exit

I have added screenshots below to help anyone figure out the location and to change the file size.
[Location](https://i1.lensdump.com/i/jvSIe2.md.png)
[sizeBefore](https://i1.lensdump.com/i/jvSZxv.md.png)
[sizeAfter](https://i1.lensdump.com/i/jvSrRC.md.png)

**Comment by mason1171** [comment]
> Can you please increase the upload size of the Zippyshare host to 500 MB?

By default the limit is 200MB. Follow these steps to fix the problem:
1. cd to the modules location
2. use 'nano' to open up zippyshare file: 'sudo nano zippyshare.sh'
3. Use CTRL+W to search for 'filesize' and edit the max file size from 200MB to 500MB (or any other size you prefer).
4. Save and exit

I have added screenshots below to help anyone figure out the location and to change the file size.
[Location](https://i1.lensdump.com/i/jvSIe2.md.png)
[sizeBefore](https://i1.lensdump.com/i/jvSZxv.md.png)
[sizeAfter](https://i1.lensdump.com/i/jvSrRC.md.png)

**Comment by mcrapet** [comment]
Not the proper repository, see plowshare-modules-legacy.
