### ISSUE TITLE
Perhaps a "git clone [...]" step is needed in the install document?

### ISSUE THREAD

**Issue by Ganton** [mcrapet/plowshare#13]
Hi!

In https://github.com/mcrapet/plowshare/blob/master/INSTALL :
    `[...]`
    `2) Manual method: from git sources`
    `# If you have root privileges (like Ubuntu)`
    `$ sudo make install`
    `[...]`
perhaps is a
    `git clone https://github.com/mcrapet/plowshare.git`
    `[...]`
or similar needed after `2) Manual method: from git sources`?

Thanks for Plowshare!

**Comment by mcrapet** [comment]
Yes, idea is good, I'll do that.
