### ISSUE TITLE
Mediafire module Broken

### ISSUE THREAD

**Issue by Morpholetto** [mcrapet/plowshare#16]
Hello, when I try to download a file with mediafire plugin, after the captcha immission I get the following error:  

parse failed (sed): "/function[[:space:]]__/ s/^._"([^"]+)";.*$/\1/p" (skip 1)
Failed inside mediafire_download(), line 316, mediafire.sh
Failed inside mediafire_download() [1

I got the last version of plowshare, installed by git 2 days ago from your fresh master branch.

Thanks so much

**Comment by mcrapet** [comment]
Hi,
Please reopen an issue in the right place:
https://github.com/mcrapet/plowshare-modules-legacy/issues
