### ISSUE TITLE
Confused about available modules. Where are they?

### ISSUE THREAD

**Issue by rdscorreia74** [mcrapet/plowshare#17]
Hi mcrapet.
First of all let me thank you a lot for creating this wonderful software that I've used some time ago.
Modules used to come bundled with the Archlinux binaries but apparently no more.
Reading your readme (https://github.com/mcrapet/plowshare/blob/master/README.md) I've noticed that the modules are now not included although you wrote that, quoting, "...few are available separately and must be installed in user directory (see below).".
Well, following the "see below" link I didn't find any modules, not even a link to an external website to get them.
So could you please clarify?
Thanks a lot. :-)
Cheers

**Comment by mcrapet** [comment]
Hi,
"see below" refers to INSTALL files.
Have a look at last section:
https://github.com/mcrapet/plowshare/blob/master/INSTALL

Regards,
Matthieu
