### ISSUE TITLE
plowmod cannot function on mac os x

### ISSUE THREAD

**Issue by ghost** [mcrapet/plowshare#18]
```
# plowmod -i https://github.com/mcrapet/plowshare-module-mega.git
mkdir: illegal option -- -
usage: mkdir [-pv] [-m mode] directory ...
# plowmod --status
mkdir: illegal option -- -
usage: mkdir [-pv] [-m mode] directory ...
```

my system is OS X 10.9.5.
Thanks

**Comment by msdos** [comment]
Would you mind creating a new bug fix release after this fix? Since this bug made plowshare useless in mac osx, I think it's a good time for a new one.

**Comment by mcrapet** [comment]
Yes I can do this. Is there a specific packaging of plowshare somewhere for osx?

**Comment by msdos** [comment]
I'm using a package manager called [homebrew](https://github.com/homebrew/homebrew), that has ruby DSL's to download your package, apply some patches and compile it.

Plowshare definition [is this one](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/plowshare.rb). Actually, by reading this code it seems a patch using mkdir from coreutils may work too (you can see it uses sed and head from coretuls as well in the patch), without the need of a new release, so it's up to you. Thanks!
