### ISSUE TITLE
Uptobox upload problem.

### ISSUE THREAD

**Issue by cleme29** [mcrapet/plowshare#20]
Hi !
Today I just had this error, so I report it to you ! :)
I took a screenshot, if you want more details, tell me.
Thanks!
![s3kxr9z](https://cloud.githubusercontent.com/assets/8092733/8397918/a3a679b0-1ddc-11e5-99fb-05d2abbcbb6e.png)

**Comment by mcrapet** [comment]
Hi,

This current repository is dedicated to core only and does not concern any modules (hosters).

Please open this issue in "plowshare-modules-legacy" repository.
Follow this guide for bug report:
https://github.com/mcrapet/plowshare-modules-legacy/wiki/Module-issue-reporting

Thanks.
