### ISSUE TITLE
plowmod with php

### ISSUE THREAD

**Issue by Halohalohalo** [mcrapet/plowshare#22]
Hi I thanks for plowshare, I just want to inform you when I executed plowshare in a php script, plowmod complains about not having modules:

<? exec("/usr/bin/plowdown http://host.com/file ") ?>

It says I had to install the modules in /.config/plowshare/modules.d/legacy.git/ 

Btw I run php + Apache with a user called "benny". And I already installed the proper modules on /home/benny/.config/plowshare/modules.d/legacy.git/ but plowmod still complains about not seeing the modules.

So I created the copied the modules to /.config/plowshare/modules.d/legacy.git and it worked.

**Comment by mcrapet** [comment]
Hi,
Could you set an environment variable with your exec, I guess that PHP has no HOME variable.

**Comment by Halohalohalo** [comment]
Ah! It's working now with:

<? exec(' "HOME="/home/benny" /usr/bin/plowdown http://host.com/file ') ?>

Thanks!
