### ISSUE TITLE
Hook for plowup

### ISSUE THREAD

**Issue by kidburglar** [mcrapet/plowshare#23]
Hi, I'm just tried to use --run-before with plowup and I see that

plowup: unknown command-line option --run-before

It is possible to add hooks for plowup ?
It can be usefull for example zip files and split or something others.

Cheers.

**Comment by mcrapet** [comment]
Hi,

For modules supporting cache (see --cache=shared) uploading one file by one file and executing your script will work. However, as the option is existing for plowdown, it could be added to plowup indeed.

**Comment by kidburglar** [comment]
Ok I taught first to script a while loop with plowup in.
But I should wait for hooks (I keep I look at the code and it's a little difficult for me ^^)
