### ISSUE TITLE
I often get curl: (55) Send failure error message when uploading from named pipe

### ISSUE THREAD

**Issue by Konstantinusz** [mcrapet/plowshare#24]
I usually want upload form named pipe, when transloading files from one filehost to another and I have only few disk space on my VPS to download files fully at first and then upload them.
However I often get "curl: (55) Send failure / broken pipe" error message when uploading from named pipe.
The pipe is fed by ffmpeg, but I got same experiences when the pipe is fed by bsdtar. I upload to depositfiles.com . 
Error message always appears at position when 40 MB of data has been uploaded. I also tried to pass a http header field - H "Transfer-Encoding: chunked" but no success.

On the producer side of the pipe:

```
mkfifo video.mkv
ffmpeg -i http://example.com/file.mkv -map_chapters -1 video.mkv
```

On the consumer side:

```
plowup  --auth="myname:mypass" depositfiles video.mkv
```

What can I do to avoid such annoyances, and make the pipe / uploading intact?

**Comment by Raziel-23** [comment]
@mcrapet I'm fairly sure that you can close this issue. We can't do anything about this, curl must know the size of file before the transfer starts. This limitation is described here curl/curl#360. The OP forgot to close this issue.
