### ISSUE TITLE
Make is not working on freebsd, error with install command

### ISSUE THREAD

**Issue by drustan** [mcrapet/plowshare#26]
root@downloader:/tmp/plowshare # make  
===[Plowshare update]===  
install -d /usr/bin  
install -d /usr/share/plowshare  
install -d /usr/share/plowshare/modules  
install -d /usr/share/doc/plowshare  
install -d /usr/share/man/man1  
install -d /usr/share/man/man5  
install -m 644  src/modules/config /usr/share/plowshare/modules  
install -m 755  /usr/share/plowshare  
usage: install [-bCcpSsUv] [-f flags] [-g group] [-m mode] [-o owner]  
               [-M log] [-D dest] [-h hash] [-T tags]  
               [-B suffix] [-l linkflags] [-N dbdir]  
               file1 file2  
       install [-bCcpSsUv] [-f flags] [-g group] [-m mode] [-o owner]  
               [-M log] [-D dest] [-h hash] [-T tags]  
               [-B suffix] [-l linkflags] [-N dbdir]  
               file1 ... fileN directory  
       install -dU [-vU] [-g group] [-m mode] [-N dbdir] [-o owner]  
               [-M log] [-D dest] [-h hash] [-T tags]  
               directory ...  
**\* [install_files] Error code 64

**Comment by capic** [comment]
Hi, on debian I have:
===[Plowshare update]===
install -d /usr/bin
install -d /usr/share/plowshare
install -d /usr/share/plowshare/modules
install -d /usr/share/doc/plowshare
install -d /usr/share/man/man1
install -d /usr/share/man/man5
install -m 644  src/modules/config /usr/share/plowshare/modules
install -m 755 src/download.sh src/upload.sh src/delete.sh src/list.sh src/probe.sh src/core.sh src/mod.sh /usr/share/plowshare
install -m 644 docs/plowdown.1 docs/plowup.1 docs/plowdel.1 docs/plowlist.1 docs/plowprobe.1 docs/plowmod.1 /usr/share/man/man1
install: cannot stat `/usr/share/man/man1/plowup.1': Input/output error
install: cannot stat`/usr/share/man/man1/plowdel.1': Input/output error
install: cannot stat `/usr/share/man/man1/plowlist.1': Input/output error
install: cannot stat`/usr/share/man/man1/plowprobe.1': Input/output error
install: cannot stat `/usr/share/man/man1/plowmod.1': Input/output error
make: **\* [install_files] Error 1

**Comment by drustan** [comment]
Here is the part I changed to be able to install it: 

[...]

MODULE_FILES = $(wildcard src/modules/*.sh) src/modules/config  
SRCS      = src/download.sh src/upload.sh src/delete.sh src/list.sh src/probe.sh src/core.sh src/mod.sh  
SRCS2      =download.sh upload.sh delete.sh list.sh probe.sh core.sh mod.sh  
MANPAGES1 = docs/plowdown.1 docs/plowup.1 docs/plowdel.1 docs/plowlist.1 docs/plowprobe.1 docs/plowmod.1  
MANPAGES5 = docs/plowshare.conf.5  
DOCS      = README.md docs/plowshare.conf.sample
[...]

[...]
$(INSTALL) -m 755 $(SRCS) $(DESTDIR)$(DATADIR)  
        $(INSTALL) -m 644 $(MANPAGES1) $(DESTDIR)$(MANDIR)1  
        $(INSTALL) -m 644 $(MANPAGES5) $(DESTDIR)$(MANDIR)5  
        $(INSTALL) -m 644 $(DOCS) $(DESTDIR)$(DOCDIR)
[...]

[...]

```
    @for file in $(SRCS2); do \                                                                                                 
            $(GNU_SED) -i -e '/\/licenses\/>/ashopt -s expand_aliases; alias sed='\''$(GNU_SED)'\' "$(DESTDIR)$(DATADIR)/$$file"
```

; \  
        done
[...]

And you a have to do this as well : mount -t fdescfs fdesc /dev/fd

**Comment by mcrapet** [comment]
Hi,

This is not clear. Could you provide a patch ?

In `INSTALL` file it is said:

<pre>
Note for BSD users (Free BSD & Mac OSX)
------------------
You must manually install from sources.
You'll need GNU make (not bmake) and gnu-sed (or gsed) installed.
Don't forget to properly define GNU_SED variable.
# For example
$ make install GNU_SED=/opt/bin/gnu-sed PREFIX=/usr
$ make patch_gnused GNU_SED=/opt/bin/gnu-sed PREFIX=/usr
</pre>

Did you follow that ?

**Comment by dR3b** [comment]
I had the same error on FreeBSD:

``` bash
~/plowshare (git)-[master] % make install GNU_SED=/usr/local/bin/gsed PREFIX=/home/admin/plowshare_bin
===[Plowshare update]===
install -d /home/admin/plowshare_bin/bin
install -d /home/admin/plowshare_bin/share/plowshare
install -d /home/admin/plowshare_bin/share/plowshare/modules
install -d /home/admin/plowshare_bin/share/doc/plowshare
install -d /home/admin/plowshare_bin/share/man/man1
install -d /home/admin/plowshare_bin/share/man/man5
install -m 644  src/modules/config /home/admin/plowshare_bin/share/plowshare/modules
install -m 755  /home/admin/plowshare_bin/share/plowshare
usage: install [-bCcpSsUv] [-f flags] [-g group] [-m mode] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               [-B suffix] [-l linkflags] [-N dbdir]
               file1 file2
       install [-bCcpSsUv] [-f flags] [-g group] [-m mode] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               [-B suffix] [-l linkflags] [-N dbdir]
               file1 ... fileN directory
       install -dU [-vU] [-g group] [-m mode] [-N dbdir] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               directory ...
*** Error code 64

Stop.
make: stopped in /usr/home/admin/plowshare
```

Any solutions or questions?

**Comment by mcrapet** [comment]
Hi,
Plowshare installation requires GNU Make, not BSD Make (bmake).

This appears to not work: `$(addprefix src/,$(SRCS))`

Maybe, could you try (with braces):
`${addprefix src/,$(SRCS)}`
or (with space after comma):
`$(addprefix src/, $(SRCS))`

**Comment by Raziel-23** [comment]
@mcrapet It doesn't work, addprefix and wildcard are GNU Make specific and doesn't exist in BSD Make. Here is my solution:
https://github.com/Raziel-23/plowshare/commit/2bf4c19d65db456ed85985fe5a9e837b70296090
This solution based on what @Drustan proposed. I tested it on my shell FreeBSD account and on Linux. I don't know if there is a better solution, but it works.

Edit: I forgot to change second for loop:
https://github.com/Raziel-23/plowshare/commit/98cd8a3483b629c25ea4a028a6714c953db1b8d9

Edit 2: My final version, replace addprefix with for loop, remove unneeded wildcard (now modules are in separate repository):
https://github.com/Raziel-23/plowshare/commit/f6a02d83c4bbae95f54255f745ecf0b30231482c

Please test it and if you think that it's good enough you can merge it.

**Comment by mcrapet** [comment]
Hi,

`$(wildcard src/modules/*.sh)` can be removed because modules are not distribued with plowshare (core) anymore.
I'll dealing with this ASAP.

**Comment by Raziel-23** [comment]
More important then `wildcard` is `addprefix`. It depends if you want to support bmake. If you leave `addprefix` then bmake will not work. I don't know if there is a better solution then replacing it with for loop.

On the side note there is a minor thing with installation instruction regarding BSD. I would change it from:

```
# For example
$ make install GNU_SED=/opt/bin/gnu-sed PREFIX=/usr
$ make patch_gnused GNU_SED=/opt/bin/gnu-sed PREFIX=/usr
```

to:

```
# For example
$ make install patch_gnused GNU_SED=/opt/bin/gnu-sed PREFIX=/usr
```

It is simpler and not trigger `install_files` rule twice.

**Comment by mcrapet** [comment]
I've added one more comment in Makefile file to tell that GNU make should be used.
I won't touch current Makefile for BSD compatibility.
