### ISSUE TITLE
How to use different network interface

### ISSUE THREAD

**Issue by Drezzler** [mcrapet/plowshare#27]
Hello , i see their is option to bind curl to network interface .

So say i have 2 networks interfaces on different IP's , for example eth1 and eth2

How would i pass the network inteface to use via the commandline ?

**Comment by mcrapet** [comment]
Hi,

This is not possible currently. I'll add this roundrobin in the wishlist.

**Comment by FailOPS** [comment]
Would be interested on this topic too. Maybe it would be a good option to have a roundrobin and also to let the user decide which IP will be used.

Eg: On some machines I got different interfaces with one IP each (maybe also used as label eth0:1) and on the other hand there are machines with only one interface, but a bunch of IP addresses.

This would be nice to see for up- and download

Cheers

**Comment by steom** [comment]
great feature!
