### ISSUE TITLE
Pass external cookie into plowshare

### ISSUE THREAD

**Issue by skinner12** [mcrapet/plowshare#30]
Hello,

I've writing nitroflare's module for upload files.

It's already done but I need to know how to pass cookie into script.

Nitroflare's login page has recaptcha 2 and I need to login into without manual insert code; so in nitroflare.sh I insert filepath of 1 cookie saved from firefox but if I want to move that file I need to change filepath inside nitroflare.sh.

How to avoid this? 

The best option is to pass the complete filepath as option in plowshare like username and password but I didn't find how; or better, I read in another ticket to use option --cache but I didn't find into wiki so I didn't know how to use this.

Any help?

**Comment by zodman** [comment]
plowshare had an  API https://github.com/mcrapet/plowshare#implement-your-own-modules

**Comment by mcrapet** [comment]
It's a quite old issue, let's close this.

`--cache` switch should be correctly documented now.
