### ISSUE TITLE
Keep2Share (k2s.cc) not working

### ISSUE THREAD

**Issue by kwaaak** [mcrapet/plowshare#35]
```
Starting download (keep2share): http://k2s.cc/file/...
grep_form_by_order failed (sed): "n=1"
Failed inside keep2share_download() [1]
```

**Comment by Raziel-23** [comment]
I cannot reproduce this issue. For me it works with this test file:  
`http://k2s.cc/file/4d4fa3125b91a/Test_file_5MB.zip`  
`$(grep_form_by_order "$PAGE")` command in keep2share module returns valid html form. Maybe your IP is blacklisted. Nevertheless please next time report such issues in plowshare-modules-legacy repository, here it is only the core, not modules/services. Please also read [Guide to Plowshare module bug report](https://github.com/mcrapet/plowshare-modules-legacy/wiki/Module-issue-reporting), maybe you missed something.

**Comment by mcrapet** [comment]
Please open issue in plowshare-modules-legacy.
