### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Machou** [mcrapet/plowshare#4]
Hello

i have this error when i want download :+1: 
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `115` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `180upload` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `1fichier` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `2shared` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `4share_vn` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `4shared` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `anonfiles` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `bayfiles` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `bayimg` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `billionuploads` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `bitshare` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `chomikuj` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `cramit` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `crocko` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `data_hu` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `dataport_cz` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `depositfiles` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `divshare` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `dl_free_fr` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `euroshare_eu` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `filebin_ca` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `filecloud` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `filecore` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `filefactory` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `fileover` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `filepost` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `filepup_net` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `filer_net` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `firedrive` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `flashx` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `freakshare` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `fshare_vn` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `gamefront` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `ge_tt` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `gfile_ru` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `hdstream_to` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `hipfile` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `keep2share` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `letitbit` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `mediafire` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `megashares` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `multiupload` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `myvdrive` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `nakido` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `netkups` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `netload_in` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `nowdownload_co` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `oboom` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `promptfile` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `rapidgator` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `rapidshare` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `rghost` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `ryushare` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `sendspace` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `sharebeast` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `shareonline_biz` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `sockshare` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `solidfiles` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `tempsend` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `thefilebay` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `turbobit` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `ultramegabit` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `uploadable_ch` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `uploadhero` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `uploading` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `uploaded_net` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `upstore` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `uptobox` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `yourvideohost` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `zalaa` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `ziddu` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `zippyshare` module overwrite, this one is taken

**Comment by mcrapet** [comment]
Hi, you probably still have modules in /usr/share/plowshare/modules or so. Please install plowshare > 2.0.1

**Comment by Machou** [comment]
Have plowshare 2.1.0 installed ^^

**Comment by mcrapet** [comment]
Delete `/usr/share/plowshare/modules` directory.

Could you paste result of `plowdown -v4 --no-color http://a`

**Comment by Machou** [comment]
i have delete the repertory (doesn't rexis :D)


plowdown -v4 --no-color http://a
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `115` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `180upload` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `1fichier` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `2shared` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `4share_vn` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `4shared` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `anonfiles` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `bayfiles` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `bayimg` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `billionuploads` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `bitshare` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `chomikuj` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `cramit` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `crocko` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `data_hu` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `dataport_cz` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `depositfiles` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `divshare` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `dl_free_fr` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `euroshare_eu` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `filebin_ca` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `filecloud` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `filecore` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `filefactory` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `fileover` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `filepost` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `filepup_net` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `filer_net` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `firedrive` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `flashx` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `freakshare` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `fshare_vn` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `gamefront` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `ge_tt` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `gfile_ru` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `hdstream_to` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `hipfile` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `keep2share` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `letitbit` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `mediafire` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `megashares` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `multiupload` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `myvdrive` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `nakido` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `netkups` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `netload_in` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `nowdownload_co` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `oboom` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `promptfile` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `rapidgator` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `rapidshare` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `rghost` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `ryushare` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `sendspace` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `sharebeast` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `shareonline_biz` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `sockshare` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `solidfiles` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `tempsend` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `thefilebay` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `turbobit` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `ultramegabit` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `uploadable_ch` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `uploadhero` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `uploading` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `uploaded_net` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `upstore` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `uptobox` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `yourvideohost` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `zalaa` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `ziddu` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `zippyshare` module overwrite, this one is taken
rep: === SYSTEM INFO BEGIN ===
rep: [mach] **.**.**x86_64 linux-gnu x86_64-pc-linux-gnu
rep: [bash] 4.3.33(1)-release
rep: [curl] curl 7.39.0 (x86_64-pc-linux-gnu) libcurl/7.39.0 OpenSSL/1.0.1l zlib/1.2.8 c-ares/1.10.0
rep: [sed ] GNU sed version 4.2.1
rep: [lib ] '/mnt/sdd1/wedont/plowshare/share/plowshare'
fatal: Not a git repository (or any parent up to mount point /mnt/sdd1)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
rep: === SYSTEM INFO END ===
rep: plowdown version v2.1.0 (2015-04-10)
Temporary directory: /home/wedont/tmp
No module found, try simple redirection
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --silent --user-agent  --head http://a
rep: Received 55 bytes. DRETVAL=6
rep: === CURL BEGIN ===
rep:curl: (6) Could not resolve: a (Domain name not found)
rep: === CURL END ===
curl: couldn't resolve host
dbg: remote server reply: curl: (6) Could not resolve: a (Domain name not found)
Skip: no module for URL (http://a)
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `directmirror` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `embedupload` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `exoshare` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `go4up` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `jheberg` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `mirrorcreator` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `mirrorupload` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `multiup_org` module overwrite, this one is taken
INFO: /home/wedont/.config/plowshare/modules.d/legacy.git/config: `pastebin` module overwrite, this one is taken

**Comment by mcrapet** [comment]
According to your libdir: /mnt/sdd1/wedont/plowshare/share/plowshare
you may have a `modules` in here to delete.
Could you do a `ls -l /home/wedont/.config/plowshare/modules.d/` ?

**Comment by Machou** [comment]
wedont@kunzite ~ $ ls -l /home/wedont/.config/plowshare/modules.d/
total 4
drwxr-xr-x 3 wedont wedont 4096 Apr 11 02:39 legacy.git

**Comment by Machou** [comment]
so ? ^^

**Comment by mcrapet** [comment]
You still have the INFO lines ? It's means that you have several sources of modules.
Find the "modules" or "modules.d" directories (for exemple /usr/local/share/plowshare/modules) and delete them.

**Comment by Machou** [comment]
now it's fixed :p
