### ISSUE TITLE
[request] a function that removes non-breaking spaces

### ISSUE THREAD

**Issue by Raziel-23** [mcrapet/plowshare#41]
When I was working on solidfiles I encountered that file size contains a [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space). Those [examples](http://superuser.com/questions/517847/use-sed-to-replace-nbsp-160-hex-00a0-octal-240-non-breaking-space) shows how to deal with them. I can use sed to remove them, but maybe it should be in the core. Feel free to close this issue if you think it is not worth.

**Comment by mcrapet** [comment]
I think I will enhance `strip()` to deal with that.

**Comment by Raziel-23** [comment]
I was rather thinking about translating all kinds of non-breaking spaces :D, including `&nbsp;`, `&#160;`, `&#xA0;`. I know that there are only 5 modules that remove `&nbsp;`. I don't know how you think, but maybe such function or enhanced strip that translate all kinds of non-breaking spaces (not only `\xC2\?\xA0`) would be more useful in the future.

**Comment by mcrapet** [comment]
`html_to_utf8` is already available.

**Comment by Raziel-23** [comment]
I didn't know about it, thanks.
