### ISSUE TITLE
image_upload_imgur: upload error

### ISSUE THREAD

**Issue by frollic** [mcrapet/plowshare#42]
dbg: uploading image to Imgur.com
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent -F image=@/tmp/download.sh.24518.29184.recaptcha.jpg -H Expect:  --form-string key=23d202e580c2f8f378bd2852916d8f30 --form-string type=file --form-string title=Plowshare uploaded image http://api.imgur.com/2/upload.json
rep: Received 160 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:{"data":{"error":"The version of the Imgur API you are using is no longer available","request":"\/2\/upload.json","method":"POST"},"success":false,"status":404}
rep: === CURL END ===
image_upload_imgur: upload error
Leave this field blank and hit enter to get another captcha image

seems they've upgraded their API - https://api.imgur.com/

changing BASE_API to https://api.imgur.com/3 in core.sh results in:

rep: Received 118 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:{"data":{"error":"Authentication required","request":"\/3\/upload.json","method":"POST"},"success":false,"status":401}
rep: === CURL END ===
image_upload_imgur: upload error

**Comment by mcrapet** [comment]
Hi,
Could you open this in the proper place:
https://github.com/mcrapet/plowshare-modules-legacy/issues

Thanks!

**Comment by Raziel-23** [comment]
@mcrapet I think this is related to the core :D, because there isn't any imgur module, and probaly he refers to this:
https://github.com/mcrapet/plowshare/blob/master/src/core.sh#L3838

**Comment by mcrapet** [comment]
OOps! Sorry!
