### ISSUE TITLE
[request]  sha1_file function

### ISSUE THREAD

**Issue by Raziel-23** [mcrapet/plowshare#43]
openload_io has an opportunity to check if sha1 sums matches after uploading file. Uploading sha1 sum is not required, but it ensures that file was uploaded correctly.

I don't know how you think, but maybe it's not a bad idea to create multihash function that accepts as first argument type of hash. This is only my loose thoughts, but maybe there are other services with different hashes.

**Comment by mcrapet** [comment]
I'll handle this. I'll update `PLOWSHARE_API_VERSION` to `4`. Could you add a version check in your module for backward compatibility?

Let's keep AGILE philosophy and don't add uneeded code. We'll see when SHA-2 or RIPEMD will be needed.

**Comment by Raziel-23** [comment]
When sha1_file function will be ready then I will put at the beginning of the upload function in openload module something like this:

```
if [ $PLOWSHARE_API_VERSION -lt 4 ]; then
    log_error 'This module requires API version 4. Please update your plowshare core to version 2.1.4 or higher.'
    return $ERR_FATAL
fi
```

**Comment by mcrapet** [comment]
Does the whole module require `sha1_file()` ? Would it be possible to enclose only the small part of code requiring sha1? Providing a "sha1-less" version would be nice for old plowshare users.

**Comment by Raziel-23** [comment]
I can make a command-line switch that enables sha1 sums checking, or simply make nothing and not implement this feature at all (it's not required). This service provides such feature and I'm sure that users would be appreciate if this would be enable by default, because it ensures that files were uploaded correctly. I highly doubt that someone is interested in uploading corrupted files.

Should I also remove new return code from this module? It may be problematic. I not only use it in login function. I also use it to check if a cookie file is valid during folder creation. I use WWW to create new folder, because API lacks such function. Normally I don't need a cookie file at all, because I use API login and API pass. In this way I don't need to cache a cookie file at all, I only need check if it's valid, otherwise I renew session. It may not be valid if someone use --cache=shared and want create new folder.

I understand you, you want to mix plowshare core in release fashion with plowshare module in git fashion. It has some benefit, but it also has drawbacks. For example I can't use new core functions because someone there use an ancient core version. It is like having new features in core that are in fact useless. I had plans about refactoring some major modules, and also new ideas about new possibilities that plowshare core can have, but I don't know what to think about it now.

**Comment by mcrapet** [comment]
Please keep `$ERR_EXPIRED_SESSION` return code. Just try to skip sha1 verification if `$PLOWSHARE_API_VERSION` is below 4. Enable this behavior by default (no module option required).
