### ISSUE TITLE
premium link

### ISSUE THREAD

**Issue by Erkalos** [mcrapet/plowshare#50]
Hi,

est ce qu'il est possible d'obtenir le lien premium d'uptobox ?

**Comment by Raziel-23** [comment]
S'il vous plaît utiliser la langue anglaise. Je ne suis pas français.

It should works if you have a premium account on uptobox. If you have problems with modules please next time report such issues [here](https://github.com/mcrapet/plowshare-modules-legacy).

**Comment by Erkalos** [comment]
Hi,
Sorry for french ^^
My question was simple : with plowdown can I just recover the link premium of uptobox ?

**Comment by mcrapet** [comment]
Hi,
You mean something like that:

<pre>plowdown --skip-final --printf %d http://uptobox.com/f5hf8r93b9dz</pre>

Which gives me:
http://www68.uptobox.com/d/4uy3jbd5enin2xsqnhbjiwz7ocg4pwbr4yijo5egflszq6f5z675orhro42skheo6p5jsryserauwydfiy/10MB.bin

And give this URL to a friend ? I think that most hosters disallow this.
There are usually checks:
- IP (the computer requesting the file and the one downloading it must be the same)
- Time validity (the generated link is usually available for few hours)
- Number of access to the generated link (final url) is limited to 1

Maybe some hosters -- and specially if you are a premium user -- are more loose.

**Comment by Erkalos** [comment]
Yes exactly that ! 
Uptobox allow (not sure for TOU) , now i can remote my some file to other hoster :)
