### ISSUE TITLE
allow concurrent downloading?

### ISSUE THREAD

**Issue by chienb** [mcrapet/plowshare#54]
Is it possible to allow concurrent downloading as of this version? Any plans to add the ability to transload links further down the roadmap? It would be great if the files aren't downloaded onto the server as waiting for large split zip files to finish takes a while.

**Comment by sasha-** [comment]
If you have SSH access to the server you can just use it as SOCKS proxy and download files to your local machine.
On your machine you would open tunnel like this:
`ssh _user_@_server_ -C -D 9999 # use any high unused port here`
Then use plowshare to download the file

```
export http_proxy=socks5://localhost:9999 # the port where you opened the tunnel
plowdown _file_name_
```

If  you have access to multiple servers, you can open multiple tunnels for concurrent  downloads.

**Comment by mcrapet** [comment]
Use shell ability to put processes in background:

<pre>
$ plowdown -q http://....  &
$ plowdown -q http://....  &
</pre>

You can also use `screen` or `tmux` it's handy!
