### ISSUE TITLE
Checking DepositFiles.com / DFiles.eu links with plowprobe sometimes gives false positive result

### ISSUE THREAD

**Issue by Konstantinusz** [mcrapet/plowshare#55]
When I attach "?redirect" to the end of the links, then it gives always proper results.

**Comment by Raziel-23** [comment]
Why do you think that this issue belongs to the core and not belongs [here](https://github.com/mcrapet/plowshare-modules-legacy)?

**Comment by mcrapet** [comment]
Hi,
Could you recreate this issue in plowshare-modules-legacy.
Thanks.

**Comment by Raziel-23** [comment]
I checked this. It always gives me an expected result to this dead link:

```
http://dfiles.eu/files/766ypdgmw?redirect
```

Without full log I don't know what was wrong. Most probably the service was temporarily down or temporarily set some sort of protection (DDoS protection or very heavy user usage protection etc.).

**Comment by Raziel-23** [comment]
@mcrapet Just reminder that you can close this, it's already fixed https://github.com/mcrapet/plowshare-modules-legacy/issues/93.
