### ISSUE TITLE
wait() is not nice to hibernation

### ISSUE THREAD

**Issue by mozbugbox** [mcrapet/plowshare#56]
The `wait` function depend on count down of sleep calls. This algorithm won't work well when the system waked up from a hibernation.

It should check epoch with `date +"%s"`, at least from time to time.

**Comment by mcrapet** [comment]
Hi,

Here is the idea:
https://gist.github.com/mcrapet/73e248cbc1ef8eb9e48f0b019825ae34

Once SIGCONT detected `wait()` is aborted. I don't want to call `$(date +%s)` each second.

On the PM side, add a file in `/etc/pm/sleep.d/90_plowshare`.

It would be something like:

<pre>
#!/bin/sh
case $1 in
    hibernate|suspend)
        # find plowdown PID and send it STOP signal
    ;;
    thaw|resume)
        # find plowdown PID and send it CONT signal
    ;;
esac
</pre>

I'm not happy with this SIGCONT solution, sometimes I do CTRL+Z on plowdown (for a short amount of time), and I don't want to abort `wait()`. Maybe a new command line flag ?

**Comment by mozbugbox** [comment]
You don't have to call `date +"%s" every seconds. You can call it every 60 secs or so:

``` sh

#!/bin/sh
wait_timeout=$((60*30)) # 30 minutes
start=`date +"%s"`
end=$(( ${start} + ${wait_timeout} ))

n=0
date_interval=60

while [ ${n} -lt ${wait_timeout} ]; do
    sleep 1
    n=$(( ${n} + 1 ))
    if [ $(( n % ${date_interval} )) -eq 0 ]; then
        now=`date +"%s"`
        if [ ${now} -ge ${end} ]; then
            break
        fi
    fi
done
```

**Comment by mozbugbox** [comment]
or you can call `date +"%s"` on a SIGCONT signal, that works too in a manual way.

**Comment by mcrapet** [comment]
@mozbugbox : could you update plowshare and test ?

**Comment by mcrapet** [comment]
No news, closing.
