### ISSUE TITLE
Switch to deactivate waiting time

### ISSUE THREAD

**Issue by fermentfan** [mcrapet/plowshare#57]
Hey,
first: thanks again for this tool! Second: Is it possible to implement a switch to deactivate the 30 seconds waiting time if you load from the same hoster between two downloads? If I download to my server I wait 3x the time I download and it should be no problem (at least with Uploaded.net.

Greetings!

**Comment by mcrapet** [comment]
Hi,

If you have a premium uploaded.net account, you should update your plowshare-modules-legacy to have this commit: https://github.com/mcrapet/plowshare-modules-legacy/commit/8b166520c177584933adc6f9fd548151a90d8d1b

**Comment by mcrapet** [comment]
Any news on this ?
