### ISSUE TITLE
bug with uploaded.net

### ISSUE THREAD

**Issue by mikrob** [mcrapet/plowshare#58]
Hi,

When i try to download to uploaded.net with a valid account (work in browser and in jdownloader) i have a parsing error.

Command : 
`plowdown -a "XXXXX:YYYYYYY" http://uploaded.net/file/abcdefghi`

Result : 

```
Starting download (uploaded_net): http://uploaded.net/fileabcdefghi
Starting login process: XXXXXXX/********
parse failed (sed): "/Status:/ s/^.*<em>\(.*\)</em>.*$/\1/p" (skip 1)
Failed inside uploaded_net_login(), line 73, uploaded_net.sh
Failed inside uploaded_net_download() [1]

```

Is it a bad use or a bug?

**Comment by Raziel-23** [comment]
It only means that you didn't update your modules, it's already fixed [here](https://github.com/mcrapet/plowshare-modules-legacy/issues/79).

**Comment by mcrapet** [comment]
`plowmod -u` should do the job.

**Comment by mcrapet** [comment]
As it is related to modules, next time, open issue here:
https://github.com/mcrapet/plowshare-modules-legacy/issues
Thanks.
