### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Machou** [mcrapet/plowshare#6]
Hello :)

new problem ^^

i have try :

root@:~/backup/plowshare4# plowmod -i
plowmod: adding legacy (default) repository: https://github.com/mcrapet/plowshare-modules-legacy.git
- installing new directory: /root/.config/plowshare/modules.d/legacy.git
  ERROR: directory exists but it does not appear to be a git repository, abort

**Comment by mcrapet** [comment]
No luck :)
It has been fixed recently with issue #5

PS: use plowmod as user not root as it stores modules in $HOME/.config/plowshare directory

**Comment by Machou** [comment]
i have make a git pull, but i have the error, i need delete all repertory ?

**Comment by Machou** [comment]
ok, i have full reinstall, i have the same problem (:

**Comment by mcrapet** [comment]
How did you reinstall from git repo or distro package? What is your git version ?

try:
$ rm -rf  /root/.config/plowshare/modules.d
$ plowmod -v3 -i
$ plowmod -v3 -u

Paste me result.

[edit: plowup => plowmod]

**Comment by Machou** [comment]
plowmod, not plowup :dancer: So:

root:/home# rm -rf /root/.config/plowshare/modules.d

root:/home# plowmod -v3 -i
plowmod: adding legacy (default) repository: https://github.com/mcrapet/plowshare-modules-legacy.git
dbg: modules directory: /root/.config/plowshare/modules.d
- installing new directory: /root/.config/plowshare/modules.d/legacy.git

root:/home# plowmod -v3 -u
dbg: modules directory: /root/.config/plowshare/modules.d
- updating directory: /root/.config/plowshare/modules.d/legacy.git
  ERROR: directory exists but it does not appear to be a git repository, abort!

**Comment by mcrapet** [comment]
It really looks like issue #5.
What is you git version ?

**Comment by Machou** [comment]
#5 & #6 is on different server

Git version on #6 git version 1.7.10.4
Git version on #5 git version 2.0.5

**Comment by mcrapet** [comment]
What is the result of:
$ cd 
$ git -C /root/.config/plowshare/modules.d/legacy.git rev-parse --is-inside-work-tree

**Comment by Machou** [comment]
root:~# git -c /root/.config/plowshare/modules.d/legacy.git rev-parse --is-inside-work-tree
fatal: Not a git repository (or any of the parent directories): .git

**Comment by mcrapet** [comment]
-C in uppercase.

Try also:
$ cd /root/.config/plowshare/modules.d/legacy.git && rev-parse --is-inside-work-tree

**Comment by Machou** [comment]
Unknown option: -C

bash: rev-parse: command not found

**Comment by Machou** [comment]
update to last version, same error x_x

maybe i need upgrade git to 2.x ?

**Comment by mcrapet** [comment]
git v1.8.5+ but plowmod is just a helper script. You can manually go into legacy.git directory and do a git pull this is what the script does..

**Comment by Machou** [comment]
how to do that ? please (sorry, i'm very noob :()

**Comment by mcrapet** [comment]
It depends your Linux distribution. You can go on google .. or IRC to ask for help.

**Comment by Machou** [comment]
Update to 1.9.1, problem solved

If anyone need help : (on Debian 7)

```
echo "deb http://http.debian.net/debian wheezy-backports main" >> /etc/apt/sources.list
apt-get update
apt-get -t wheezy-backports install git
```
