### ISSUE TITLE
generated bytecode for method exceeds 64K limit

### ISSUE THREAD

**Issue by xeyizegat** [mcrapet/plowshare#61]
Hello

First: Thanks for your work!

Running into a bug/problem when trying to download from openload.co
Installed rhino because the javascript interpreter is needed...

But eventually I get this error:

`js: "/tmp/download.sh.8073.15294.js", line 1: Encountered code generation error while compiling script: generated bytecode for method exceeds 64K limit.`

Any idea?

Regards!

**Comment by mcrapet** [comment]
Hi!
You'll probably need to change your javascript interpreter:
https://github.com/mcrapet/plowshare-modules-legacy/issues/92
