### ISSUE TITLE
Issue with premium upstore downloading

### ISSUE THREAD

**Issue by dindox12** [mcrapet/plowshare#62]
Dear mcrapet,

First of all thank you for your work. I always appreciate well written bash code. 
I have a problem with downloading a premium file with upstore premium account. As I read from the man pages the correct syntax should be:
`plowdown -a 'myuser:mypassword' https://upstore.net/foo`
The response I get from the script is the following:

```
Starting download (upstore): https://upstore.net/foo
Starting login process: myuser/********
Insufficient permissions (private/premium link)
```

From what I understood the script is logging me in as free account. In fact the script does work in the case I try to download a file not restricted only to premium users. Further more in the case I try to download a file bigger than 2gb this is the response I have:

```
Starting download (upstore): https://upstore.net/foo
Starting login process: myuser/********
Unexpected remote error: File size is larger than 2 GB. Unfortunately, it can be downloaded only with premium
Failed inside upstore_download() [1]
```

Maybe I just need to add a cookie option when I call the command or a javascript interpreter. Nevertheless I decided to open this issue since I had no clue on how to find a solution. 
Hope you can help, have a nice day.

**Comment by mcrapet** [comment]
Hi,

This place is dedicated to plowshare core not modules.

Please create issue here (proper place)
https://github.com/mcrapet/plowshare-modules-legacy/issues

Please do read:
https://github.com/mcrapet/plowshare-modules-legacy/blob/master/CONTRIBUTING.md
for proper bug report.

Thanks!
