### ISSUE TITLE
plowdown - turbobit.net - parse failed (sed) error

### ISSUE THREAD

**Issue by aycanuAydemir** [mcrapet/plowshare#63]
Hi,

I get the following error when trying to download files from the turbobit.net:
# plowdown http://turbobit.net//download/redirect/228642CB67BC02E496CF41BCA25DD18Dp/7tfohvudg2yn

Starting download (turbobit): http://turbobit.net//download/redirect/228642CB67BC02E496CF41BCA25DD18Dp/7tfohvudg2yn
parse failed (sed): "/<title>/ s/^[[:blank:]]_Download (.+). Free._$/\1/p" (skip 1)
Failed inside turbobit_download(), line 136, turbobit.sh
Failed inside turbobit_download() [1]

Please help me..

**Comment by mcrapet** [comment]
Hi,

This place is dedicated to plowshare core not modules.

Please create issue here (proper place)
https://github.com/mcrapet/plowshare-modules-legacy/issues

Please do read:
https://github.com/mcrapet/plowshare-modules-legacy/blob/master/CONTRIBUTING.md
for proper bug report.

Thanks!
