### ISSUE TITLE
[Question] Can Plowshare handle huge ammount of Uploads?

### ISSUE THREAD

**Issue by dobaniashish** [mcrapet/plowshare#65]
Hello @mcrapet ,

I have been using Plowshare to download files continuously on my server for long times and my server was able to download files without high load. Now I want to use plowshare for upload to lots of sites continuously. I would like to know if it can handle lots of uploading too? Has anyone used plowup for longer periods?

Is there any thing I should take care of before starting this. What are the precautions to be taken?

Thank You,
Ashish Dobani.

**Comment by mcrapet** [comment]
Hi,

Plowshare relies on curl, so network issues can append. plowup has an option to automatically retry on failure: `-r/--max-retries`, it can wise for you to put a positive value (like 10). In any way, if plowup fails you can the exit status will be non 0 (`$?` in shell).

On a module point of view, all modules do not support cache mechanism [1], It means that I you upload 100 files on a hoster with an account, you'll login 100 times. Hosters are more and more paranoid about this and easily ban IP addresses. Neither, all modules supports premium account.

---

[1] https://github.com/mcrapet/plowshare-modules-legacy/blob/master/README.md (:recycle: icon)

**Comment by dobaniashish** [comment]
Hello,

Thanks for putting on the light. This information helps alot. I will try to start the uploading process and post back the results in a few days.

Moreover, I would like to know if there is any JAVA alternative to plowshare. I found a JAVA based one named "neembuu uploader" but the project is dead. Another one (not based on JAVA) is zoom uploader, but it is for windows.

Thank You,
Ashish Dobani.
