### ISSUE TITLE
catshare.sh: sed: -e expression #1, char 56: Invalid range end

### ISSUE THREAD

**Issue by 6Xkljk8Vj7Tk1k4** [mcrapet/plowshare#66]
Waiting 60 seconds... done
sed: -e expression #1, char 56: Invalid range end
parse failed (sed): "/recaptcha._?k=/ s/^._?k=([[:alnum:]_-.]+).*$/\1/p" (skip 0)
Failed inside catshare_download(), line 117, catshare.sh
Failed inside catshare_download() [1]

**Comment by mcrapet** [comment]
Hi,
This is the repository for core engine only. For modules related issues, please open an issue here:
https://github.com/mcrapet/plowshare-modules-legacy/issues

Please do read [CONTRIBUTING.md](https://github.com/mcrapet/plowshare-modules-legacy/blob/master/CONTRIBUTING.md), **How to submit a bug ?** section.

Thanks.
