### ISSUE TITLE
Disable forced wait?

### ISSUE THREAD

**Issue by hcuk94** [mcrapet/plowshare#67]
If I run plowdown on a .txt list of RapidGator links, between each download it says 'Same previous hosted, forced wait requested' and waits 35 minutes until it will download the next file.

I don't recall any such limitation on RG and if I use plowdown individually it happily downloads straight away.

Is there a way I can disable the forced wait and have plowdown download the next link in the list immediately?

Thanks

**Comment by mcrapet** [comment]
Sure, go in module [source](https://github.com/mcrapet/plowshare-modules-legacy/blob/master/rapidgator.sh) et set `MODULE_RAPIDGATOR_DOWNLOAD_SUCCESSIVE_INTERVAL` to 0.

**Comment by hcuk94** [comment]
Excellent, thanks very much!
