### ISSUE TITLE
FileFactory Error

### ISSUE THREAD

**Issue by hcuk94** [mcrapet/plowshare#70]
I'm getting the following error when using FileFactory. Any ideas?
`parse_attr failed (sed): "/data-delay/ data-delay="`
`Failed inside filefactory_download(), line 113, filefactory.sh`
`Failed inside filefactory_download() [1]`

Thanks

**Comment by zodman** [comment]
can you put the command with verbose option and  complete output!

**Comment by hcuk94** [comment]
I've uploaded the verbose output here:
[output.txt](https://github.com/mcrapet/plowshare/files/614249/output.txt)
Have removed personal info. Hope someone can help.

**Comment by zodman** [comment]
can you provide a url  to download and reproduce the problem please

**Comment by zodman** [comment]
wait! the repository correct to report the issue its on  https://github.com/mcrapet/plowshare-modules-legacy

here is the core plowshare ...

**Comment by mcrapet** [comment]
Indeed, this is not the proper repository!
Thanks zodman.
