### ISSUE TITLE
Little error when I do a make install

### ISSUE THREAD

**Issue by kidburglar** [mcrapet/plowshare#77]
Hello,
I have a little error when I do a make install.
I don't know very well the syntax so I prefer to change it myself.

`/bin/sh: 1: scripts/version: Permission denied
Makefile:76: recipe for target 'patch_git_version' failed
`
Edit:
I don't know why I only have the problem now because I see in the repo that the line in the makefile exist from a very long time... But if you have idea and test I will well try in case we not find why I will well bypass it in the Makefile.

Cheers

**Comment by mcrapet** [comment]
`scripts/version` must have executable permission.If you downloaded plowshare through a .zip files permissions will be lost.

**Comment by kidburglar** [comment]
Mmm I'm sure the problem come from some permission but I cannot find where (it's on another driver mount with special groups so it's a little tricky. But we cannot use a shell like /bin/sh directly in the Makefile in place of execute the script ? If you find the question useless you may close the issue if you want.

**Comment by mcrapet** [comment]
> Mmm I'm sure the problem come from some permission but I cannot find where
`version` is the only file required by makefile to have executable permission.

> But we cannot use a shell like /bin/sh directly in the Makefile in place of execute the script ? 
It could be a possible workaround for you.
