### ISSUE TITLE
Rapidgator module broken

### ISSUE THREAD

**Issue by mblais** [mcrapet/plowshare#8]
`rep: === SYSTEM INFO BEGIN ===
rep: [mach] eeepc i486 linux-gnu i486-pc-linux-gnu
rep: [bash] 4.2.37(1)-release
rep: [curl] curl 7.26.0 (i486-pc-linux-gnu) libcurl/7.26.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.25 libssh2/1.4.2 librtmp/2.3
rep: [sed ] GNU sed version 4.2.1
rep: [lib ] '/usr/share/plowshare4'
rep: === SYSTEM INFO END ===
rep: plowdown version v1.0.5
Output directory: /mnt/sdb1/aTrans/wget
plowdown: force captcha method (imgur)
Starting download (rapidgator): http://rapidgator.net/file/7a4169699acaba78db270eb273d2baab/1793.rar.html
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent --limit-rate 100000 -b /tmp/plowdown.27161.19543 -c /tmp/plowdown.27161.19543 -d lang=en -o /dev/null http://rapidgator.net/site/lang
rep: Received 0 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep: === CURL END ===
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent --limit-rate 100000 --include -b /tmp/plowdown.27161.19543 -c /tmp/plowdown.27161.19543 http://rapidgator.net/file/7a4169699acaba78db270eb273d2baab/1793.rar.html
rep: Received 229 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:HTTP/1.1 302 Moved Temporarily
rep:Cache-Control: no-cache
rep:Location: /file/7a4169699acaba78db270eb273d2baab/1793.rar.html?zF18d724e3e4f352a1668bfb5893d75c98=00d0e39da028a327c14feaf558f01ef4
rep:Content-Length: 0
rep:Connection: close
rep:
rep: === CURL END ===
parse failed (sed): "/var fid/ s/^._=[[:space:]]+([[:digit:]]+)._$/\1/p" (skip 0)
Failed inside rapidgator_download(), line 331, rapidgator.sh
Failed inside rapidgator_download() [1]

`

**Comment by mcrapet** [comment]
You should update your plowshare version.
Open module issue in plowshare-modules-legacy.

**Comment by mblais** [comment]
My apologies for my newbness. Thank you for your patience. All working now. 

Debian `apt-get` gets a very old version, apparently. Using `git clone` and `make install` works much better.
