### ISSUE TITLE
Use custom path to modules ?

### ISSUE THREAD

**Issue by PietroDR** [mcrapet/plowshare#82]
At the moment, modules are installed in user directory. But my problem is that www-data user can't install modules properly with plowmod and I don't want to create a directory in /var/www.
Would it be possible to use a custom path to modules ?

**Comment by mcrapet** [comment]
Hi,
Actually it's not exported (it uses `$XDG_CONFIG_HOME`).
Edit `core.sh` line 28 and change to your need:

<pre>
# User configuration directory (contains plowshare.conf, exec/, storage/, modules.d/)
declare -r PLOWSHARE_CONFDIR="${XDG_CONFIG_HOME:-$HOME/.config}/plowshare"
</pre>

**Comment by PietroDR** [comment]
Thank you, it works like a charm !
