### ISSUE TITLE
Which dependencies are safe to remove?

### ISSUE THREAD

**Issue by woerndl** [mcrapet/plowshare#83]
When I installed plowshare via brew it came with the dependencies `readline, bash, coreutils, gnu-sed, pkg-config, libtool, xz, libpng, libtiff, freetype, imagemagick, libcaca, gettext, recode, nspr, spidermonkey`

> Few dependencies and portable. Bash and cURL are enough for most hosters.

Since cURL and Bash (in my case on OS X) should be enough for most hosters, is it safe to uninstall the other dependencies or do you recommend keeping some?

I'm thinking especially about bash and coreutils, since I'd like to avoid conflicts with the native bash on OS X.

**Comment by mcrapet** [comment]
Hi,

`bash`, `curl`, `gnu-sed` are enough. Some modules use javascript interpreter (`spidermonkey` or else).
For displaying captchas, an image viewer should be available (several are supported, see manual).
`coreutils` should not be required.

**Comment by mcrapet** [comment]
No news, good news! Closing.
