### ISSUE TITLE
pay for websites like youtube

### ISSUE THREAD

**Issue by arashdehghan2** [mcrapet/plowshare#84]
Hello Matthieu Crapet !
can you please creat module for youtube and other sites like this??
i can pay for that if you give it private

**Comment by zodman** [comment]
why not use youtube-dl ?

**Comment by mcrapet** [comment]
Hi,
I don't maintain `plowshare` anymore, and ever less `plowshare-modules`. This has been a great bash adventure for me. As @zodman said, there are many tools around.

Regards,
Matthieu
