### ISSUE TITLE
Issue with timing out using Plowdown

### ISSUE THREAD

**Issue by futuresushi** [mcrapet/plowshare#85]
Hello! I installed plowshare around a month and a half ago and had absolutely no issues around installation time but right now, no matter which service I'm trying to use, I'm getting timeout warnings:

```
[agrius ~] plowdown -v4 http://uploaded.net/file/9t9au0k3/star.vs.the.forces.of.evil.s02e22.720p.hdtv.x264-w4f.mkv
rep: === SYSTEM INFO BEGIN ===
rep: [mach] agrius x86_64 linux-gnu x86_64-pc-linux-gnu
rep: [bash] 4.3.30(1)-release
rep: [curl] curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
rep: [sed ] License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
rep: [lib ] '/media/sdp/futuresushi/share/plowshare'
rep: === SYSTEM INFO END ===
rep: plowdown version v2.1.6-11-g82cab22 (2017-01-05)
dbg: plowdown: --no-overwrite selected
plowdown: force captcha method (imgur)
rep: use /media/sdp/futuresushi/.config/plowshare/plowshare.conf
Starting download (uploaded_net): http://uploaded.net/file/9t9au0k3/star.vs.the.forces.of.evil.s02e22.720p.hdtv.x264-w4f.mkv
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent --interface eth1 --head http://uploaded.net/file/9t9au0k3/star.vs.the.forces.of.evil.s02e22.720p.hdtv.x264-w4f.mkv
rep: Received 58 bytes. DRETVAL=28
rep: === CURL BEGIN ===
rep:curl: (28) Connection timed out after 240828 milliseconds
rep: === CURL END ===
curl: HTTP retrieve error
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent --interface eth1 -i http://uploaded.net/file/9t9au0k3/star.vs.the.forces.of.evil.s02e22.720p.hdtv.x264-w4f.mkv
```

it just repeats the last part until the max timeout.

What is the likeliest source of the issue?

**Comment by mcrapet** [comment]
Hi
Use `-t` switch to set a timeout.
Are you behind a proxy ?

Is this working ?
`curl --interface eth1 -i http://uploaded.net`

**Comment by kidburglar** [comment]
It's maybe not related but I had few time out issues with 1fichier too.
Now I use -v4 if it come back I will look the logs.

**Comment by futuresushi** [comment]
@mcrapet I have the interface and a timeout set in my conf file, which currently stands as follows:

`###
### Plowshare configuration file
###
[General]
interface = eth1
rapidgator/b = '{login info removed}'
[Plowdown]
timeout=23600
no-overwrite=1
captchamethod=imgur`

obviously just with the actual login info there.

I'm not behind a proxy as far as I know. My seedbox isn't having any other speed / throttle issues as far as I can tell either.

I just tried it again with a blank config file (after initially just ruling out the timeout) and it seems to be working now. Will report back in a moment.

EDIT: Removing 'interface = eth1' fixed the issue. Was that just formatted wrong?
