### ISSUE TITLE
ERROR: directory exists but it does not appear to be a git repository, abort

### ISSUE THREAD

**Issue by rmulr** [mcrapet/plowshare#87]
Hi,

- centos 7
- git version 1.8.3.1

Got the following error
```
plowmod --install
plowmod: adding legacy (default) repository: https://github.com/mcrapet/plowshare-modules-legacy.git
- installing new directory: /root/.config/plowshare/modules.d/legacy.git
[root@dsone plowshare]# plowmod --update
- updating directory: /root/.config/plowshare/modules.d/legacy.git
ERROR: directory exists but it does not appear to be a git repository, abort!

```
plowmod -s
Found modules locations:
- /usr/share/plowshare/modules (no module detected)
- /root/.config/plowshare/modules.d/legacy.git (108 modules found)
[root@dsone legacy.git]# plowup filejoker
plowup: unsupported module (filejoker)
plowup: try `plowup --modules' to see available modules.
[root@dsone legacy.git]# 
```

and plowup --modules' shows up modules i dont even know from which directory.

any idea, whats wrong?
```

**Comment by mcrapet** [comment]
Greetings,
You need git 1.8.5+ for plowmod.

See issue #6.

**Comment by rmulr** [comment]
I did, now latest Git install. Error gone but still not using latest modules. Not sure what i am doing wrong. 

i did 
make install
plowmod -i
plowmod -u

`[root@dsone plowshare]# plowmod -s
Found modules locations:
- /usr/share/plowshare/modules (no module detected)
- /root/.config/plowshare/modules.d/legacy.git (108 modules found)
[root@dsone plowshare]# 

`
`[root@dsone plowshare]# plowup filejoker
plowup: unsupported module (filejoker)
plowup: try `plowup --modules' to see available modules.
`

**Comment by zodman** [comment]
02:32:32 root@136591:4:~ # plowup --modules | grep joker
yeap the filejoker its not supported! if you want create a issue on legacy modules repo.

**Comment by rmulr** [comment]
? why there is FileJoker.sh in modules and a lot of others but when i use plowup --modules only the default/old ones get shown?

**Comment by rmulr** [comment]
`[root@dsone ~]# git clone https://github.com/mcrapet/plowshare.git
Klone nach 'plowshare' ...
remote: Counting objects: 17872, done.
remote: Total 17872 (delta 0), reused 0 (delta 0), pack-reused 17872
Empfange Objekte: 100% (17872/17872), 9.19 MiB | 3.81 MiB/s, Fertig.
Löse Unterschiede auf: 100% (11019/11019), Fertig.
[root@dsone ~]# cd plowshare/
[root@dsone plowshare]# make install
install -d /usr/bin
install -d /usr/share/plowshare
install -d /usr/share/plowshare/modules
install -d /usr/share/doc/plowshare
install -d /usr/share/man/man1
install -d /usr/share/man/man5
install -m 644  src/modules/config /usr/share/plowshare/modules
install -m 755 src/download.sh src/upload.sh src/delete.sh src/list.sh src/probe.sh src/core.sh src/mod.sh /usr/share/plowshare
install -m 644 docs/plowdown.1 docs/plowup.1 docs/plowdel.1 docs/plowlist.1 docs/plowprobe.1 docs/plowmod.1 /usr/share/man/man1
install -m 644 docs/plowshare.conf.5 /usr/share/man/man5
install -m 644 README.md docs/plowshare.conf.sample /usr/share/doc/plowshare
ln -sf /usr/share/plowshare/download.sh /usr/bin/plowdown
ln -sf /usr/share/plowshare/upload.sh   /usr/bin/plowup
ln -sf /usr/share/plowshare/delete.sh   /usr/bin/plowdel
ln -sf /usr/share/plowshare/list.sh     /usr/bin/plowlist
ln -sf /usr/share/plowshare/probe.sh    /usr/bin/plowprobe
ln -sf /usr/share/plowshare/mod.sh      /usr/bin/plowmod
[root@dsone plowshare]# plowmod
plowmod: no action specified!
plowmod: try `plowmod --help' for more information.
[root@dsone plowshare]# plowmod -u
plowmod: no directory found, have you invoked `plowmod --install' first?
[root@dsone plowshare]# plowmod --install
plowmod: adding legacy (default) repository: https://github.com/mcrapet/plowshare-modules-legacy.git
- installing new directory: /root/.config/plowshare/modules.d/legacy.git
[root@dsone plowshare]# plowmod --update
- updating directory: /root/.config/plowshare/modules.d/legacy.git
[root@dsone plowshare]# plowup --modules | grep filejoker
[root@dsone plowshare]# plowup filejoker
plowup: unsupported module (filejoker)
plowup: try `plowup --modules' to see available modules.
[root@dsone plowshare]# `

**Comment by mcrapet** [comment]
Go [there](https://github.com/mcrapet/plowshare-modules-legacy) and look at README (bottom of the page).
You'll see that filejoker is handled for plowdown only (and with an account).
`plowdown --modules` will list filejoker.
`plowup --modules` will not list filejoker.

**Comment by rmulr** [comment]
Whats the problem with upload?

**Comment by mcrapet** [comment]
There's no problem, it's just unimplemented!

**Comment by rmulr** [comment]
Ok, no problem i will use something else.
