### ISSUE TITLE
Additional parameter: stop download after a specific number of bytes were transfered

### ISSUE THREAD

**Issue by knutshub** [mcrapet/plowshare#9]
Is it possible to add a parameter to define that only a specific number of bytes are downloaded?

I think it can be done with the curl parameter:

curl --range 0-10485760 ...
for the first 10M.

**Comment by mcrapet** [comment]
Hi,
This is a custom usage of plowdown you can uses hooks with 
`plowdown --skip-final --run-after xxx` see README.md for examples.

**Comment by knutshub** [comment]
OK. Thanks for the hint. I will try this with an own small bash script.

**Comment by knutshub** [comment]
Ok. Problem solved. If someone is interested here is my code:

```
$ cat finalcurl.sh
```

```
#!/bin/bash
# $1: module name
# $2: download URL
# $3: cookie file fulfilled by download module function
# $4: final download URL
# $5: final filename (no path: --output-directory is ignored)
# You can print messages to stderr. stdout will be trashed
curl --cookie $3 --range 0-10485760 --output TEST_OUTPUT.out $4
```

Then run:

```
$ plowdown --skip-final --run-after ./finalcurl.sh <URL>
```
