### ISSUE TITLE
[Feature Request] [Plowdown] min-rate

### ISSUE THREAD

**Issue by gentano** [mcrapet/plowshare#91]
Hi,

is it possible to add min-rate and configurable timeout for plowdown?

E. g. Download speed is slower/= X kb/s for longer then X seconds = disconnect from server and try X other times. Saw the min-rate feature on plowup and really wondered why it doesnt exist for plowdown :)

Background for request: Im having issues with Zippyshare: 4..5 files are downloading at full speed (100mbit) and then it drops to between several and 300kb/s. Closing the session (Im using PortableGIT under Windows 10) and restart the download will make it fast again. Im pretty sure its Zippyshare or Providers fault, but that feature would be cool anyway for any related problems like this example.

**Comment by mcrapet** [comment]
Hi gentano,
Could you test it?

**Comment by gentano** [comment]
Hey Matthieu,

it works great - thank You very much! Could You add an option for 
timeout tho (its fixed value of 30sec for both min-rate and max-rate at 
the moment) or if You dont want to add an option where can I change the 
value, please?


Am 02.04.2017 um 16:05 schrieb Matthieu Crapet:

**Comment by gentano** [comment]
Is it this:

     if test -n "$MIN_LIMIT_RATE"; then
         OPTIONS+=(--speed-time 30 --speed-limit $MIN_LIMIT_RATE)

?

:-)

So could I just use the --speed-time option like the --min-rate option?



Am 02.04.2017 um 16:05 schrieb Matthieu Crapet:

**Comment by mcrapet** [comment]
`--speed-time 30` is a curl switch, you could tweak the value here (`core.sh`) if you like.

**Comment by gentano** [comment]
Hey Matthieu,

is it possible to add a function, so it will automatically retry a 
download after it failed because of too slow speed, maybe even 
chooseable if retry at the end of the queue or just immediately?


Thanks,

gentano


Am 02.04.2017 um 16:05 schrieb Matthieu Crapet:
