### ISSUE TITLE
 bad flag in substitute command

### ISSUE THREAD

**Issue by webdevguy525** [mcrapet/plowshare#92]
Hi I have installed plowshare
and plowdown gives me error
Please check 
cloud:~ administrator$ plowdown --modules
sed: 1: "/^[^#]/{/|[[:space:]]*d ...": bad flag in substitute command: '}'
sed: 1: "/^[^#]/{/|[[:space:]]*d ...": bad flag in substitute command: '}'
what can i do 
thanks

**Comment by mcrapet** [comment]
Hi,
Please give me more details. On what platform are you ? Linux, BSD ?
Did you installed modules (documented in INSTALL file) ?

**Comment by webdevguy525** [comment]
I am using mac os. El Captain

**Comment by webdevguy525** [comment]
I installed module, and it is in /Users/administrator/.config/plowshare/modules.d/legacy.git

**Comment by webdevguy525** [comment]
Can you let me know how to install the plowshare in mac os correctly?

**Comment by webdevguy525** [comment]
ok, i solved the problem. 
Do you have the module for openload.co and dailyuploads.net?

**Comment by mcrapet** [comment]
Fine.
Regarding modules, I think openload.co is currently broken.
See issues on the modules repositoty:
https://github.com/mcrapet/plowshare-modules-legacy/issues

**Comment by webdevguy525** [comment]
also turbobit, i can't use premium account. the credential is right, but it says bad username and password, do you have any solution?
