### ISSUE TITLE
"--cache shared" does nothing on rapidgator

### ISSUE THREAD

**Issue by marianvlad** [mcrapet/plowshare#99]
Hi,

I'm trying to upload files on rapidgator using cache for preventing multiple logins. I'm using ```plowup --cache shared -a "username:password" rapidgator /path/file``` and the cache file it is not generated in ```/.config/plowshare/storage/rapidgator.txt```

**Comment by mcrapet** [comment]
Hi,

Your question is about a module, so next time open an issue on plowshare-modules-legacy.

Go here: https://github.com/mcrapet/plowshare-modules-legacy and go on the bottom of the page, you'll see capabilities of modules. Look for *session management*, this icon: :recycle: means that `--cache=shared` is implemeted. This is not the case for rapidgator.

Regards,
m
